version: "3.8"
services:
  mysql:
    image: mysql:9.2
    container_name: mysql-jwt
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: demo_security_jwt
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - jwt-net

volumes:
  db_data:

networks:
  jwt-net:
